'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';

import { useAuth } from '@/features/auth/auth-provider';
import { ResourceLayout } from '@/features/operations/resource-layout';
import { ApiError } from '@/lib/api-client';

import { getRiskDashboard, recalculateRisk } from './risk-api';
import { HighRiskClientList, HighRiskStaffList, RecentRiskAlerts } from './components/risk-lists';
import { RiskMetricGrid } from './components/risk-metric-grid';
import { RiskSummaryCard } from './components/risk-summary-card';

export function RiskPage() {
  const auth = useAuth();
  const queryClient = useQueryClient();
  const accessToken = auth.accessToken ?? '';
  const [error, setError] = useState<string | null>(null);
  const queryKey = ['risk-dashboard', accessToken];

  const dashboardQuery = useQuery({
    queryKey,
    queryFn: () => getRiskDashboard(accessToken),
    enabled: Boolean(accessToken),
  });

  const recalculateMutation = useMutation({
    mutationFn: () => recalculateRisk(accessToken),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey });
    },
    onError: (caughtError: unknown) => {
      setError(
        caughtError instanceof ApiError ? caughtError.message : 'Risk recalculation failed.',
      );
    },
  });

  const dashboard = dashboardQuery.data;

  return (
    <ResourceLayout
      description="Review operational risk scores, trends, and high-risk entities generated by the rule-based scoring engine."
      title="Risk Dashboard"
    >
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <p className="text-sm text-slate-600">
          {dashboard?.generatedAt
            ? `Last generated ${new Date(dashboard.generatedAt).toLocaleString()}`
            : 'Generate scores to populate the dashboard.'}
        </p>
        <button
          className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-60"
          disabled={recalculateMutation.isPending}
          onClick={() => {
            setError(null);
            recalculateMutation.mutate();
          }}
          type="button"
        >
          {recalculateMutation.isPending ? 'Recalculating...' : 'Recalculate risk'}
        </button>
      </div>

      {error ? (
        <p className="mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          {error}
        </p>
      ) : null}

      {dashboard ? (
        <div className="grid gap-6">
          <RiskSummaryCard
            label="Agency operational risk"
            level={dashboard.agencyRiskScore.riskLevel}
            score={dashboard.agencyRiskScore.score}
          />
          <RiskMetricGrid metrics={dashboard.metrics} />
          <div className="grid gap-6 lg:grid-cols-2">
            <HighRiskStaffList items={dashboard.highRiskStaff} />
            <HighRiskClientList items={dashboard.highRiskClients} />
          </div>
          <RecentRiskAlerts items={dashboard.recentAlerts} />
        </div>
      ) : (
        <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">
          {dashboardQuery.isLoading
            ? 'Loading risk dashboard...'
            : 'No risk dashboard data yet.'}
        </div>
      )}
    </ResourceLayout>
  );
}
